import { useEffect, useState } from "react";
import PropTypes from "prop-types";
import LanguageContext from "./portfolioLanguageContext";

const translations = {
  en: {
    nav: { home: "Home", about: "About", skills: "Skills", projects: "Projects", experience: "Experience", education: "Education", contact: "Contact" },
    menu: "Open navigation menu",
    eyebrow: "FULL-STACK DEVELOPER",
    heroTitle: "Building thoughtful digital experiences.",
    heroBody: "I’m Ahmed Hassan, a developer who enjoys turning ideas into responsive, useful web applications. I work across the frontend and backend, with a focus on clean interfaces and maintainable code.",
    available: "Open to opportunities",
    viewProjects: "View my projects",
    contactMe: "Contact me",
    stackLabel: "TOOLS I WORK WITH",
    aboutTitle: "A little about me",
    aboutLead: "Curious by nature. Developer by choice.",
    aboutBody: "My journey into software development grew from a love of solving problems and making ideas usable. I build with JavaScript, React, Node.js, and modern CSS, and I enjoy shaping the full experience—from a clear interface to the logic behind it. I’m continuing to learn, strengthen my engineering practice, and grow into a thoughtful software professional.",
    aboutTags: ["User-focused interfaces", "Responsive web", "Design to code", "Always learning"],
    skillsTitle: "Technical skills",
    skillsIntro: "The tools and technologies I’ve worked with so far.",
    skills: { frontend: "Frontend", backend: "Backend & data", tools: "Tools & collaboration", javascript: "JavaScript", react: "React", responsive: "Responsive design", tailwind: "Tailwind CSS", html: "HTML", css: "CSS", node: "Node.js", mongodb: "MongoDB", sql: "SQL", express: "Express.js", git: "Git", github: "GitHub", figma: "Figma", trello: "Trello", slack: "Slack" },
    projectsTitle: "Selected projects",
    projectsIntro: "A selection of things I’ve built and shipped.",
    projectLabels: { bookmark: "A lightweight bookmark manager built with HTML, CSS, and JavaScript.", tracker: "A task tracking application built with React, Tailwind CSS, and JavaScript.", calculator: "A practical calculator with an interactive interface, built with React and CSS.", counter: "A small React application demonstrating interactive state and counter controls.", login: "A polished login page interface built with React and Tailwind CSS." },
    liveDemo: "Live demo",
    sourceCode: "Source code",
    experienceTitle: "Experience",
    experienceIntro: "A clear view of my professional journey.",
    experienceListLabel: "Professional experience",
    experiences: [
      { title: "Full-Stack Developer", organization: "Alight Coding Program", location: "Kirehe / Mahama, Rwanda", dates: "2024–2025", bullets: ["Developed responsive web applications using modern frontend and backend technologies.", "Built and integrated REST APIs for full-stack applications.", "Worked with JavaScript, React, Node.js, Express.js, MongoDB, and Git/GitHub.", "Designed user-friendly interfaces with responsive layouts and reusable components.", "Worked on e-commerce, learning management, task management, booking, and social-media-style projects.", "Practiced debugging, testing, version control, and collaborative software development.", "Applied software development principles to practical, real-world problems."] },
      { title: "Coding & AI Trainee", organization: "Maison Shalom", location: "Rwanda", dates: "August–December 2025", bullets: ["Developed programming skills through practical software-development projects.", "Explored artificial intelligence concepts and their applications in software development.", "Strengthened problem-solving, programming, and technical communication skills.", "Worked with modern development tools and technologies through hands-on learning."] },
      { title: "SQL & Database Management Trainee", organization: "Maison Shalom", location: "Rwanda", dates: "February 2026–Present", bullets: ["Studying SQL and relational database concepts through practical exercises.", "Writing SQL queries for data retrieval, filtering, sorting, and analysis.", "Learning database design, relationships, and data management.", "Applying database concepts to software-development projects."] },
      { title: "ICT Trainee", organization: "CED ICT", location: "Rwanda", dates: "February–May 2026", bullets: ["Strengthened practical computer and information technology skills.", "Worked with productivity and digital tools.", "Developed technical problem-solving and digital literacy skills.", "Applied ICT knowledge to software-development and professional tasks."] },
    ],
    educationTitle: "Education & certifications",
    educationIntro: "Academic background and professional learning.",
    educationHeading: "Education",
    schoolName: "Sudanese Evangelical School",
    schoolCredential: "Secondary School Certificate",
    schoolYear: "2017",
    schoolCountry: "Sudan",
    schoolSummary: "Completed secondary education with an English-language curriculum, developing strong communication, academic, and analytical skills.",
    schoolCertificateAlt: "Scanned Sudanese Secondary School Certificate",
    viewCertificate: "View certificate",
    certificatesHeading: "Certifications",
    certificates: [
      { title: "Full-Stack Web Development Certificate", issuer: "Alight Coding Program", location: "Rwanda", description: "Completed practical training in modern full-stack web development, including frontend development, backend development, databases, APIs, and software development practices." },
      { title: "Coding with AI Certificate", issuer: "Maison Shalom", location: "Rwanda", description: "Completed practical training focused on programming and the use of Artificial Intelligence in software development and problem-solving." },
      { title: "English for Global Opportunities Certificate", issuer: "", location: "", description: "Completed professional English-language training focused on communication, workplace interaction, and preparation for international opportunities." },
      { title: "SQL & Database Management Certificate", issuer: "Maison Shalom", location: "Rwanda", description: "Completed training in SQL and database management, including querying, data organization, relational databases, and practical database operations." },
    ],
    contactTitle: "Let’s build something meaningful.",
    contactIntro: "Have a role, project, or idea in mind? I’d be glad to hear from you.",
    emailLabel: "Email",
    phoneLabel: "Phone",
    nameLabel: "Your name",
    emailFieldLabel: "Your email",
    messageLabel: "Your message",
    namePlaceholder: "Name",
    emailPlaceholder: "you@example.com",
    messagePlaceholder: "Tell me a little about what you have in mind...",
    sendMessage: "Send message",
    sending: "Sending…",
    messageSent: "Thanks for reaching out. Your message has been sent.",
    messageFailed: "Your message could not be sent. Please email me directly.",
    github: "GitHub",
    footerRole: "Full-Stack Developer",
    footerNote: "Designed and built with care.",
    notFound: "Page not found",
    backHome: "Back to home",
  },
  ar: {
    nav: { home: "الرئيسية", about: "نبذة عني", skills: "المهارات", projects: "المشاريع", experience: "الخبرة", education: "التعليم", contact: "تواصل" },
    menu: "فتح قائمة التنقل",
    eyebrow: "مطوّر متكامل الواجهات والأنظمة",
    heroTitle: "أبني تجارب رقمية مدروسة.",
    heroBody: "أنا أحمد حسن، مطوّر أستمتع بتحويل الأفكار إلى تطبيقات ويب متجاوبة وعملية. أعمل على الواجهات الأمامية والخلفية، مع اهتمام خاص بوضوح التصميم وسهولة صيانة الشيفرة.",
    available: "منفتح على الفرص المهنية",
    viewProjects: "استعرض مشاريعي",
    contactMe: "تواصل معي",
    stackLabel: "تقنيات أعمل بها",
    aboutTitle: "نبذة عني",
    aboutLead: "فضولي بطبعي، ومطوّر باختياري.",
    aboutBody: "بدأت رحلتي في تطوير البرمجيات بدافع حبي لحل المشكلات وتحويل الأفكار إلى تجارب عملية. أعمل باستخدام JavaScript وReact وNode.js وتقنيات CSS الحديثة، وأهتم ببناء التجربة كاملة، من وضوح الواجهة إلى منطق التطبيق. أواصل التعلّم وتطوير ممارستي الهندسية والنمو كمطوّر برمجيات محترف.",
    aboutTags: ["واجهات تتمحور حول المستخدم", "تطبيقات ويب متجاوبة", "تحويل التصميم إلى شيفرة", "تعلّم مستمر"],
    skillsTitle: "المهارات التقنية",
    skillsIntro: "أدوات وتقنيات عملت بها حتى الآن.",
    skills: { frontend: "الواجهة الأمامية", backend: "الواجهة الخلفية والبيانات", tools: "الأدوات والتعاون", javascript: "JavaScript", react: "React", responsive: "تصميم متجاوب", tailwind: "Tailwind CSS", html: "HTML", css: "CSS", node: "Node.js", mongodb: "MongoDB", sql: "SQL", express: "Express.js", git: "Git", github: "GitHub", figma: "Figma", trello: "Trello", slack: "Slack" },
    projectsTitle: "مشاريع مختارة",
    projectsIntro: "مجموعة من التطبيقات التي طوّرتها ونشرتها.",
    projectLabels: { bookmark: "مدير إشارات مرجعية بسيط باستخدام HTML وCSS وJavaScript.", tracker: "تطبيق لمتابعة المهام باستخدام React وTailwind CSS وJavaScript.", calculator: "آلة حاسبة عملية بواجهة تفاعلية باستخدام React وCSS.", counter: "تطبيق React صغير يوضّح إدارة الحالة والتفاعل مع العدّاد.", login: "واجهة تسجيل دخول أنيقة باستخدام React وTailwind CSS." },
    liveDemo: "التجربة المباشرة",
    sourceCode: "الشيفرة المصدرية",
    experienceTitle: "الخبرة المهنية",
    experienceIntro: "عرض واضح لمسيرتي المهنية.",
    experienceListLabel: "الخبرة المهنية",
    experiences: [
      { title: "مطوّر متكامل الواجهات والأنظمة", organization: "برنامج Alight للبرمجة", location: "Kirehe / Mahama، رواندا", dates: "2024–2025", bullets: ["تطوير تطبيقات ويب متجاوبة باستخدام تقنيات حديثة للواجهات الأمامية والخلفية.", "بناء واجهات REST API ودمجها في تطبيقات متكاملة.", "العمل باستخدام JavaScript وReact وNode.js وExpress.js وMongoDB وGit/GitHub.", "تصميم واجهات سهلة الاستخدام بتخطيطات متجاوبة ومكوّنات قابلة لإعادة الاستخدام.", "العمل على مشاريع للتجارة الإلكترونية وإدارة التعلّم والمهام والحجوزات والشبكات الاجتماعية.", "ممارسة تصحيح الأخطاء والاختبار وإدارة الإصدارات والتطوير التعاوني.", "تطبيق مبادئ تطوير البرمجيات على مشكلات عملية من الواقع."] },
      { title: "متدرّب في البرمجة والذكاء الاصطناعي", organization: "Maison Shalom", location: "رواندا", dates: "أغسطس–ديسمبر 2025", bullets: ["تطوير مهارات البرمجة من خلال مشاريع عملية في تطوير البرمجيات.", "استكشاف مفاهيم الذكاء الاصطناعي وتطبيقاتها في تطوير البرمجيات.", "تعزيز مهارات حل المشكلات والبرمجة والتواصل التقني.", "التدرّب عملياً على أدوات وتقنيات تطوير حديثة."] },
      { title: "متدرّب في SQL وإدارة قواعد البيانات", organization: "Maison Shalom", location: "رواندا", dates: "فبراير 2026–حتى الآن", bullets: ["دراسة SQL ومفاهيم قواعد البيانات العلائقية من خلال تمارين عملية.", "كتابة استعلامات SQL لاسترجاع البيانات وتصفيتها وترتيبها وتحليلها.", "تعلّم تصميم قواعد البيانات والعلاقات وإدارة البيانات.", "تطبيق مفاهيم قواعد البيانات على مشاريع تطوير البرمجيات."] },
      { title: "متدرّب في تقنية المعلومات والاتصالات", organization: "CED ICT", location: "رواندا", dates: "فبراير–مايو 2026", bullets: ["تعزيز المهارات العملية في الحاسوب وتقنية المعلومات.", "استخدام أدوات الإنتاجية والأدوات الرقمية.", "تطوير مهارات حل المشكلات التقنية والثقافة الرقمية.", "تطبيق معارف تقنية المعلومات والاتصالات في مهام تطوير البرمجيات والعمل المهني."] },
    ],
    educationTitle: "التعليم والشهادات",
    educationIntro: "الخلفية الأكاديمية والتعلّم المهني.",
    educationHeading: "التعليم",
    schoolName: "المدرسة الإنجيلية السودانية",
    schoolCredential: "شهادة المرحلة الثانوية",
    schoolYear: "2017",
    schoolCountry: "السودان",
    schoolSummary: "أكملت المرحلة الثانوية بمنهج يُدرّس باللغة الإنجليزية، وطوّرت مهارات قوية في التواصل والدراسة والتحليل.",
    schoolCertificateAlt: "صورة ممسوحة ضوئياً لشهادة المرحلة الثانوية السودانية",
    viewCertificate: "عرض الشهادة",
    certificatesHeading: "الشهادات المهنية",
    certificates: [
      { title: "شهادة تطوير الويب المتكامل", issuer: "Alight Coding Program", location: "رواندا", description: "أكملت تدريباً عملياً في تطوير الويب المتكامل الحديث، شمل تطوير الواجهات الأمامية والخلفية وقواعد البيانات وواجهات API وممارسات تطوير البرمجيات." },
      { title: "شهادة البرمجة باستخدام الذكاء الاصطناعي", issuer: "Maison Shalom", location: "رواندا", description: "أكملت تدريباً عملياً ركّز على البرمجة واستخدام الذكاء الاصطناعي في تطوير البرمجيات وحل المشكلات." },
      { title: "شهادة اللغة الإنجليزية للفرص العالمية", issuer: "", location: "", description: "أكملت تدريباً مهنياً في اللغة الإنجليزية ركّز على التواصل والتفاعل في بيئة العمل والاستعداد للفرص الدولية." },
      { title: "شهادة SQL وإدارة قواعد البيانات", issuer: "Maison Shalom", location: "رواندا", description: "أكملت تدريباً في SQL وإدارة قواعد البيانات، شمل الاستعلامات وتنظيم البيانات وقواعد البيانات العلائقية والعمليات العملية عليها." },
    ],
    contactTitle: "لنبنِ شيئاً ذا معنى معاً.",
    contactIntro: "لديك وظيفة أو مشروع أو فكرة؟ يسعدني أن أسمع منك.",
    emailLabel: "البريد الإلكتروني",
    phoneLabel: "الهاتف",
    nameLabel: "اسمك",
    emailFieldLabel: "بريدك الإلكتروني",
    messageLabel: "رسالتك",
    namePlaceholder: "الاسم",
    emailPlaceholder: "you@example.com",
    messagePlaceholder: "أخبرني قليلاً عمّا تفكر فيه...",
    sendMessage: "إرسال الرسالة",
    sending: "جارٍ الإرسال…",
    messageSent: "شكراً لتواصلك. تم إرسال رسالتك.",
    messageFailed: "تعذّر إرسال رسالتك. يُرجى مراسلتي مباشرةً عبر البريد الإلكتروني.",
    github: "GitHub",
    footerRole: "مطوّر متكامل الواجهات والأنظمة",
    footerNote: "صُمّم وطُوّر بعناية.",
    notFound: "الصفحة غير موجودة",
    backHome: "العودة إلى الرئيسية",
  },
  fr: {
    nav: { home: "Accueil", about: "À propos", skills: "Compétences", projects: "Projets", experience: "Expérience", education: "Formation", contact: "Contact" },
    menu: "Ouvrir le menu de navigation",
    eyebrow: "DÉVELOPPEUR FULL-STACK",
    heroTitle: "Je conçois des expériences numériques utiles.",
    heroBody: "Je suis Ahmed Hassan, développeur passionné par la création d’applications web accessibles et réactives. J’interviens côté frontend et backend, avec une attention particulière portée aux interfaces claires et au code maintenable.",
    available: "Ouvert aux opportunités",
    viewProjects: "Voir mes projets",
    contactMe: "Me contacter",
    stackLabel: "TECHNOLOGIES UTILISÉES",
    aboutTitle: "À propos de moi",
    aboutLead: "Curieux de nature, développeur par choix.",
    aboutBody: "Mon parcours dans le développement logiciel est né du plaisir de résoudre des problèmes et de rendre les idées concrètes. Je développe avec JavaScript, React, Node.js et les outils CSS modernes. J’aime concevoir une expérience complète, de l’interface à la logique applicative. Je continue à apprendre, à affiner ma pratique et à progresser comme ingénieur logiciel.",
    aboutTags: ["Interfaces centrées sur l’utilisateur", "Web adaptatif", "Du design au code", "Apprentissage continu"],
    skillsTitle: "Compétences techniques",
    skillsIntro: "Les outils et technologies que j’ai utilisés jusqu’ici.",
    skills: { frontend: "Frontend", backend: "Backend et données", tools: "Outils et collaboration", javascript: "JavaScript", react: "React", responsive: "Design adaptatif", tailwind: "Tailwind CSS", html: "HTML", css: "CSS", node: "Node.js", mongodb: "MongoDB", sql: "SQL", express: "Express.js", git: "Git", github: "GitHub", figma: "Figma", trello: "Trello", slack: "Slack" },
    projectsTitle: "Projets sélectionnés",
    projectsIntro: "Quelques applications que j’ai développées et mises en ligne.",
    projectLabels: { bookmark: "Un gestionnaire de favoris léger, réalisé avec HTML, CSS et JavaScript.", tracker: "Une application de suivi des tâches réalisée avec React, Tailwind CSS et JavaScript.", calculator: "Une calculatrice pratique à interface interactive, réalisée avec React et CSS.", counter: "Une petite application React illustrant la gestion d’état et un compteur interactif.", login: "Une interface de connexion soignée, réalisée avec React et Tailwind CSS." },
    liveDemo: "Démo en ligne",
    sourceCode: "Code source",
    experienceTitle: "Expérience",
    experienceIntro: "Un aperçu clair de mon parcours professionnel.",
    experienceListLabel: "Expérience professionnelle",
    experiences: [
      { title: "Développeur Full-Stack", organization: "Alight Coding Program", location: "Kirehe / Mahama, Rwanda", dates: "2024–2025", bullets: ["Développement d’applications web adaptatives avec des technologies modernes côté frontend et backend.", "Création et intégration d’API REST pour des applications Full-Stack.", "Utilisation de JavaScript, React, Node.js, Express.js, MongoDB et Git/GitHub.", "Conception d’interfaces accessibles avec des mises en page adaptatives et des composants réutilisables.", "Participation à des projets de commerce en ligne, de gestion de l’apprentissage, des tâches, de réservation et de réseau social.", "Pratique du débogage, des tests, du contrôle de version et du développement collaboratif.", "Mise en pratique des principes du développement logiciel sur des problèmes concrets."] },
      { title: "Stagiaire en programmation et IA", organization: "Maison Shalom", location: "Rwanda", dates: "Août–décembre 2025", bullets: ["Développement des compétences en programmation au travers de projets pratiques.", "Découverte des concepts d’intelligence artificielle et de leurs applications au développement logiciel.", "Renforcement des compétences en résolution de problèmes, programmation et communication technique.", "Prise en main d’outils et de technologies de développement modernes."] },
      { title: "Stagiaire SQL et gestion de bases de données", organization: "Maison Shalom", location: "Rwanda", dates: "Février 2026–aujourd’hui", bullets: ["Étude de SQL et des bases de données relationnelles à travers des exercices pratiques.", "Rédaction de requêtes SQL pour extraire, filtrer, trier et analyser des données.", "Apprentissage de la conception des bases de données, des relations et de la gestion des données.", "Application des concepts de bases de données à des projets de développement logiciel."] },
      { title: "Stagiaire en TIC", organization: "CED ICT", location: "Rwanda", dates: "Février–mai 2026", bullets: ["Renforcement des compétences pratiques en informatique et en technologies de l’information.", "Utilisation d’outils numériques et de productivité.", "Développement de la résolution de problèmes techniques et de la culture numérique.", "Application des connaissances en TIC aux tâches de développement logiciel et aux activités professionnelles."] },
    ],
    educationTitle: "Formation et certifications",
    educationIntro: "Parcours académique et apprentissages professionnels.",
    educationHeading: "Formation",
    schoolName: "Sudanese Evangelical School",
    schoolCredential: "Certificat de fin d’études secondaires",
    schoolYear: "2017",
    schoolCountry: "Soudan",
    schoolSummary: "Études secondaires suivies dans un cursus anglophone, avec le développement de solides compétences en communication, en travail académique et en analyse.",
    schoolCertificateAlt: "Copie numérisée du certificat d’études secondaires soudanais",
    viewCertificate: "Voir le certificat",
    certificatesHeading: "Certifications",
    certificates: [
      { title: "Certificat de développement web Full-Stack", issuer: "Alight Coding Program", location: "Rwanda", description: "Formation pratique au développement web Full-Stack moderne, couvrant le frontend, le backend, les bases de données, les API et les pratiques de développement logiciel." },
      { title: "Certificat de programmation avec l’IA", issuer: "Maison Shalom", location: "Rwanda", description: "Formation pratique axée sur la programmation et l’utilisation de l’intelligence artificielle dans le développement logiciel et la résolution de problèmes." },
      { title: "Certificat d’anglais pour des opportunités internationales", issuer: "", location: "", description: "Formation professionnelle en anglais axée sur la communication, les échanges en milieu professionnel et la préparation aux opportunités internationales." },
      { title: "Certificat SQL et gestion de bases de données", issuer: "Maison Shalom", location: "Rwanda", description: "Formation en SQL et gestion de bases de données : requêtes, organisation des données, bases relationnelles et opérations pratiques." },
    ],
    contactTitle: "Construisons quelque chose qui compte.",
    contactIntro: "Vous avez un poste, un projet ou une idée ? Je serais ravi d’en discuter.",
    emailLabel: "E-mail",
    phoneLabel: "Téléphone",
    nameLabel: "Votre nom",
    emailFieldLabel: "Votre e-mail",
    messageLabel: "Votre message",
    namePlaceholder: "Nom",
    emailPlaceholder: "vous@exemple.com",
    messagePlaceholder: "Parlez-moi de votre projet ou de votre idée...",
    sendMessage: "Envoyer le message",
    sending: "Envoi en cours…",
    messageSent: "Merci pour votre message. Il a bien été envoyé.",
    messageFailed: "L’envoi a échoué. Vous pouvez m’écrire directement par e-mail.",
    github: "GitHub",
    footerRole: "Développeur Full-Stack",
    footerNote: "Conçu et développé avec soin.",
    notFound: "Page introuvable",
    backHome: "Retour à l’accueil",
  },
};

export function LanguageProvider({ children }) {
  const [locale, setLocale] = useState(() => {
    try {
      const savedLocale = window.localStorage.getItem("portfolio-language");
      return translations[savedLocale] ? savedLocale : "en";
    } catch {
      return "en";
    }
  });

  useEffect(() => {
    const direction = locale === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = locale;
    document.documentElement.dir = direction;
    document.body.dir = direction;
    try {
      window.localStorage.setItem("portfolio-language", locale);
    } catch {
      // The selected language still works when storage is unavailable.
    }
  }, [locale]);

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t: translations[locale] }}>
      {children}
    </LanguageContext.Provider>
  );
}

LanguageProvider.propTypes = { children: PropTypes.node.isRequired };